### ISSUE TITLE
python3.4  pyssdb0.4.1 

### ISSUE THREAD

**Issue by Ling1992** [ifduyue/pyssdb#24]
ssdb = pyssdb.Client('127.0.0.1', 8888)
print(ssdb.get('asdf'))

next:

Traceback (most recent call last):
  File "/home/ling/Documents/pythonDocument/py_local_ip_pool/test.py", line 19, in <module>
    print(ssdb.get('asdf'))
  File "/home/ling/Documents/pythonDocument/evn/.env1/lib/python3.4/site-packages/pyssdb.py", line 191, in wrapper
    data = func(self, cmd, *args)
  File "/home/ling/Documents/pythonDocument/evn/.env1/lib/python3.4/site-packages/pyssdb.py", line 215, in execute_command
    connection.send(cmd, *args)
  File "/home/ling/Documents/pythonDocument/evn/.env1/lib/python3.4/site-packages/pyssdb.py", line 98, in send
    buf = utf8('').join(utf8('%d\n%s\n') % (len(i), i) for i in args) + utf8('\n')
  File "/home/ling/Documents/pythonDocument/evn/.env1/lib/python3.4/site-packages/pyssdb.py", line 98, in <genexpr>
    buf = utf8('').join(utf8('%d\n%s\n') % (len(i), i) for i in args) + utf8('\n')
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

**Comment by ifduyue** [comment]
@Ling1992 Hello, pyssdb only supports Python 2.6/2.7/3.5/3.6

**Comment by Ling1992** [comment]
@ifduyue thanks
